sonar.host.url=https://sonar.tools.sap

sonar.projectKey=dl-coe-bkg-rdfantic-e2d68
sonar.projectName=bkg-rdfantic

# Paths are relative to the sonar-project.properties file
sonar.sources=src
sonar.tests=tests
sonar.test.inclusions=**/*test*.py

sonar.python.version=3.12
sonar.python.coverage.reportPaths=junit/cobertura-coverage.xml

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

# Project meta data
sonar.links.scm=https://github.tools.sap/DL-COE/bkg-rdfantic
sonar.links.issue=https://jira.tools.sap/projects/BKG/issues
