"""Base model for RDFantic providing RDF serialization and SHACL export capabilities."""

from __future__ import annotations

import warnings
from typing import TYPE_CHECKING, ClassVar, get_type_hints

from pydantic import BaseModel, ConfigDict, PrivateAttr
from rdflib import Graph, Node

from rdfantic.exceptions import RdfanticModelError
from rdfantic.internal.state import RdfanticState
from rdfantic.models.metadata import RdfanticModelMetadata

if TYPE_CHECKING:
    from rdfantic.context.base import MaterializationContext
    from rdfantic.context.shacl import ShaclMaterializationContext


class RdfanticBaseModel(BaseModel):
    """Base class that declares Meta as a required class variable.

    Implements the Resolvable protocol without inheriting from it
    to avoid metaclass conflicts between BaseModel and Protocol.
    """

    # Declare Meta as a ClassVar - subclasses should define this
    Meta: ClassVar[RdfanticModelMetadata]

    # Container for all RDFantic framework-specific state
    _rdfantic_state: RdfanticState = PrivateAttr(default_factory=RdfanticState)

    model_config = ConfigDict(arbitrary_types_allowed=True, extra="allow")

    def __init_subclass__(cls, **kwargs):
        """Validate that subclass doesn't shadow the rdf_term property and check for nested lists."""
        super().__init_subclass__(**kwargs)

        # Check if 'rdf_term' is defined as a field in the subclass
        # Note: model_fields is empty here, so we check annotations directly
        if "rdf_term" in getattr(cls, "__annotations__", {}):
            warnings.warn(
                f"{cls.__name__} defines an 'rdf_term' field which shadows "
                f"RdfanticBaseModel.rdf_term property. This will prevent access to "
                f"the RDF term generated by Meta.term_builder. "
                f"Consider renaming your field.",
                UserWarning,
                stacklevel=2,
            )

        # Check for nested lists in field annotations
        # Note: model_fields is not populated yet in __init_subclass__, so use get_type_hints()
        # to properly resolve stringified annotations (from `from __future__ import annotations`)
        try:
            hints = get_type_hints(cls, include_extras=True)
        except Exception:  # noqa: BLE001
            # If we can't resolve type hints (e.g., due to forward references), skip validation
            hints = {}

        from rdfantic.internal.type_analyzer import TypeAnalyzer  # noqa: PLC0415

        for field_name, annotation in hints.items():
            if TypeAnalyzer.contains_nested_list(annotation):
                raise RdfanticModelError(
                    f"Field '{field_name}' in {cls.__name__} contains a nested list type. "
                    f"Nested lists (e.g., list[list[T]] or list[T | list[S]]) are not supported in RDFantic. "
                    f"Consider flattening your data structure."
                )

    @property
    def rdfantic(self) -> RdfanticState:
        """Get the RDFantic framework state container.

        Returns
        -------
        RdfanticState
            Container with framework-specific state (id, parent, ctx, path).
        """
        return self._rdfantic_state

    @property
    def instance_name(self) -> str | None:
        """Get the instance name for path building in nested models.

        Returns the result of Meta.instance_name callable if defined, otherwise None.
        Used to construct path elements when serializing nested models.
        """
        if self.Meta.instance_name:
            return self.Meta.instance_name(self)
        return None

    @property
    def rdf_term(self) -> Node:
        """Get the RDF term for this model instance.

        Returns
        -------
        Node
            The RDF term (URI or BNode or Literal) for this instance.
        """
        return self.Meta.term_builder(self)

    def model_dump_rdf(
        self: RdfanticBaseModel,
        context: MaterializationContext,
        parent: RdfanticBaseModel | None = None,
        predicates: set | None = None,
        inverse: bool = False,
    ) -> Graph:
        """Serialize this model instance to an RDF graph.

        Parameters
        ----------
        context : MaterializationContext
            The materialization context used for URI resolution and creation.
        parent : RdfanticBaseModel | None, optional
            The parent model instance for nested serialization.
        predicates : set | None, optional
            Set of predicates linking parent to this instance.
        inverse : bool, optional
            Whether to create inverse (incoming) relationships. When True, triples are
            created with this instance as subject and parent as object, reversing the
            direction. Default is False.

        Returns
        -------
        Graph
            An RDFLib Graph representing this model instance.

        Raises
        ------
        ValueError
            If predicates are provided without a parent instance.
        RdfanticSerializationError
            If inverse is True but the value is not a URIRef or RdfanticBaseModel
            (literals cannot appear in subject position).

        Example
        -------
        ```python
        from sap_bkg_core.rdfantic.context import ShaclMaterializationContext

        context = ShaclMaterializationContext("http://example.org/")
        graph = instance.model_dump_rdf(context=context)
        ```
        """
        from rdfantic.serialization.rdf_serializer import RdfSerializer  # noqa: PLC0415

        return RdfSerializer.model_dump_rdf(self, context, parent, predicates, inverse)

    @classmethod
    def model_dump_shacl(cls, context: ShaclMaterializationContext) -> Graph:
        """Generate SHACL graph for this model.

        Parameters
        ----------
        context : ShaclMaterializationContext
            Context for SHACL generation. The context's `strict` attribute
            controls whether strict type constraints are enforced.

        Returns
        -------
        Graph
            RDF graph containing SHACL shape definitions.
        """
        from rdfantic.serialization.shacl_generator import ShaclGenerator  # noqa: PLC0415

        return ShaclGenerator.model_dump_shacl(cls, context)
